### PR TITLE
Pull Request to merge the following

### PR DESCRIPTION
**Pull request by MoreHeapSpace**
Please consider the following changes to merge to master:
. Add ability to disable SSO through servlet config parameter
.If we're not in a windows environment OR the browser making the request is not on a windows OS, resume filter chain
. Added check for DELETE action to isNtlmType1PostAuthorizationHeader a IE will strip the body onchallenge
. Minor changes to code format and logging: No need to prefix logger calls with 'NegotiateSecurityFilter' as it's local to the class

### CODE REVIEW

**Comment by hazendaz** [comment]
@MoreHeapSpace Please restore the formatting as it was.  I'll be happy to take the change after.

**Comment by hazendaz** [comment]
'NegotiateSecurityFilter' indicates static.  It's there on purpose.
Javadoc formating is per our checkstyle rules.  One line on properties rather tha multiple.

Thanks.

**Comment by pedroneil** [comment]
Hello, it is possilbe to have a linux domain joined browser that will send a user's Windows Credentials to the Tomcat Server. I understand that if the Server isn't on Windows, then the JNA platform probably won't be on the Servlet server.
I hope you would consider splitting the SSO rule or remove the short circuit based on forcing OS to Windows
2 init-params might be
enableSSO: true
supportedOS: windows
or just make it a list like the providers
enableSSO: 
  windows
  redhat-linux

**Comment by MoreHeapSpace** [comment]
Thanks all for the feedback.
I've reverted the changes you requested, and have updated the docs and release notes.

**Comment by pedroneil** [comment]
you should not force the browser os to be windows. chromium on both Windows and Linux support negotiate.  @see https://www.chromium.org/developers/design-documents/http-authentication.

I currently use a negated regular expression so the starts with approach breaks my use of the servlet.

**Comment by hazendaz** [comment]
I agree.  I missed that when I first looked.  Can you pull that part over to a separate pull request and look over prior suggestions on that piece?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
PR is being closed here and items that can come in differently are over on #636

**Pull request closed without merging**
