### PR TITLE
Implement ServiceLoader for creating a cache

### PR DESCRIPTION
**Pull request by simon04**
This allows users of this library to provide a different implementaiton of the cache, e.g., based on Guava or with a database backend.

### CODE REVIEW

**Comment by simon04** [comment]
@hazendaz, what do you think?

**Comment by hazendaz** [comment]
@simon04 Its probably ok.  Can you add documentation of how to achieve using a different cache?

**Comment by simon04** [comment]
@hazendaz, thanks. I've added the relevant information as Javadoc in `Cache#newCache` and a short note in the FAQ.

**Comment by hazendaz** [comment]
@simon04 Can you add markdown link directly to the source code? I know I missed seeing that when I was looking at the code and I get not wanting to duplicate documentation so having that link to the source would work well.

I presume overriding would work in this fashion so you might want to add that too for those unfamilar with this.  I'm not super familiar with it so a bit of guessing here.

- It will search my artifact (ear, war, jar, spring boot jar) for that file before it will search for default in waffle

Since that is an assumption on my part, clarity there would help others.

May I also ask what was the motivation here?  Do you have a specific cache in mind?  Maybe even an example stating what one might do easily enough.  I think that all would help users out.  For a general stand point this would effectively change no existing behaviour so I'm fine with the code and do appreciate the work.  Once this is satisfactory for helping end user out, I'll get a release shortly after so you can have this as you have waited for some time.  Sorry I forgot to come back to this thing :)

**Comment by simon04** [comment]
Sorry for the long silence. I've added a link to the FAQ to the Javadoc of the Cache class.

To mention another project using the `ServiceLoader`, `slf4j` uses it to obtain a logging provider, see https://github.com/qos-ch/slf4j/blob/e2c29c81df6fb405a3c5a6dfd1cf28ba26a7c1d6/slf4j-api/src/main/java/org/slf4j/LoggerFactory.java#L101-L107

My motivation: in a project I'm already using Google Guava. Thus, instead of pulling in another 860 KB dependency (Caffeine Cache), I'd rather use Guava's Cache implementation.

**Comment by hazendaz** [comment]
Thanks @simon04. Merging now.   I can almost have a good laugh on going back to google guava.  If I recall that is what we had to start with and someone wanted it out as it is so large.  And I think caffeine was the straight replacement probably from the google guava code if I'm not mistaken.  Anyway, this helps.  Thanks so much on this.  I'm sure others will find it useful.  Its always good to remove libraries one doesn't need if another works and I'm sure you are using guava for far more than this :)

**Comment by simon04** [comment]
Great, thank you for developing and maintaining this helpful, working-out-of-the-box library!

**Pull request merged**
