### PR TITLE
Downgrade slf4j to 1.7.x

### PR DESCRIPTION
**Pull request by pkoenig10**
Versions 1.8.x and 2.x are incompatible with older versions. The vast majority of libraries are still using 1.7.x because the 2.x releases are still in beta.

This PR downgrades SLF4J to the latest 1.7.x and updates the dependabot configuration to prevent upgrades to the 1.8.x and 2.x versions.

### CODE REVIEW

**Comment by hazendaz** [comment]
@pkoenig10 Remove the dependabot setting, that is not why it was upgraded.  I did that on purpose.  Dependabot will not suggest non release artifacts.  I'll take the downgrade though given all the CVEs on logback that have muddied the waters and fact that logback is broken entirely for groovy post alpha 4 on purpose with now 2 years of logback not fixing it.

**Comment by hazendaz** [comment]
@pkoenig10 Also make sure if I have logback in here anywhere that you are addressing that as well.  Thanks.

**Comment by hazendaz** [comment]
@pkoenig10 Thanks, will merge once build completes.  Was intending to do this at some point.  For last few years had been using mixed only as it pertained to usage of spring boot but recently logback has been getting many CVEs and even though full usage of new here outside spring boot would get those patches, as I noted, reality is that lots of features are entirely broken in logback 1.3.0 after alpha4 and honestly don't trust that Ceki will ever release slf4j/logback or really let the community drive any of it.  Great framework but not very open source friendly.

**Comment by hazendaz** [comment]
@pkoenig10 There is some issue in jetty module that is crashing this out.  I did a quick check locally so I think there is a code issue to address.  I'm just going ot merge this and then pull it locally and see what needs fixed.  THis should only be broken for maybe a half hour here while I fiddle with it.  Thanks.

**Comment by pkoenig10** [comment]
Thanks! I appreciate the quick review and merge.

Once you've fixed the failures, would it be possible to cut a new release with this change?

**Comment by hazendaz** [comment]
I can push one this weekend, its long over due for an update.

**Pull request merged**
