### PR TITLE
Fixes for #2522

### PR DESCRIPTION
**Pull request by FarmGeek4Life**
WIP, not ready for merge yet.

Partial fix for #2522 - currently a code example for review before duplicating for other packages.

TODO:
* Polish code
* Propagate change to other package (waffle-jna/src/main/java/waffle/util/cache/Cache.java)
* Add link to the custom cache FAQ page in log message
* Add text to the custom cache FAQ page detailing thread.setContextClassLoader(CacheSupplier.class.getClassLoader()) workaround, and mentioning the log message text for searching

### CODE REVIEW

**Comment by hazendaz** [comment]
I like the idea.

**Comment by hazendaz** [comment]
May want to log the exception though since it won't throw one after this change.  No need to wrap it either I don't think I. That cause which would further help others.

**Comment by FarmGeek4Life** [comment]
Well, the only exception in this case would be the "NoSuchElement"
exception. How much should we write? Just the message, or do we have it do
the full exception?

**Comment by FarmGeek4Life** [comment]
Added changes:
* Log exception as well (changed from warning to error)
* Propagate change to other package (waffle-jna/src/main/java/waffle/util/cache/Cache.java)
* Add link to the custom cache FAQ page in log message

**Comment by hazendaz** [comment]
@FarmGeek4Life After looking at this on a much bigger screen, I understand.  I think this is good enough.  I'm going to merge once its green on the build and will release it shortly after.  Cheers!

**Pull request merged**
