### PR TITLE
Dispose of guest WindowsIdentity when guest login is disabled

### PR DESCRIPTION
**Pull request by krisse7**
The same fix was done for `waffle.servlet.NegotiateSecurityFilter` and `waffle.jaas.WindowsLoginModule` in commit 8339251e.

### CODE REVIEW

**Comment by hazendaz** [comment]
@krisse7 Not sure I completely follow.  How does this change made any difference?  Unless I'm missing something here its the same code moved into the try block but doesn't use anything from that try block thus creating extra object for GC at least.  Is there a behavioural issue here?

**Comment by dblock** [comment]
> @krisse7 Not sure I completely follow. How does this change made any difference? Unless I'm missing something here its the same code moved into the try block but doesn't use anything from that try block thus creating extra object for GC at least. Is there a behavioural issue here?

It executes the `finally` block upon `return`, which either `ctx.revertToSelf` or disposes of `windowsIdentity`. Or I am missing something :)

```
if (this.impersonate && ctx != null) {
                    NegotiateSecurityFilter.LOGGER.debug("terminating impersonation");
                    ctx.revertToSelf();
                } else {
                    windowsIdentity.dispose();
                }
```

**Comment by hazendaz** [comment]
@dblock Thanks!  I see now.  Would it be more clear if it just ran 'windowsIdentity.dispose();' where it is rather than fall through that block?  Its always going to be that one but pretty far down to see right away.  Given adding it earlier adds an extra line.

**Comment by dblock** [comment]
> @dblock Thanks! I see now. Would it be more clear if it just ran 'windowsIdentity.dispose();' where it is rather than fall through that block? Its always going to be that one but pretty far down to see right away. Given adding it earlier adds an extra line.

I don't have a preference, as long as we do it the same way everywhere. Would leave that to future improvements since this fixes a bug.

**Comment by hazendaz** [comment]
Fair enough!  Will add a separate issue to address later.  I think using try/finally there is a bit confusing for future cleanup efforts since its not really something that feels normal but do agree it needs done everywhere to be correct and this fixes a bug likely introduced as that try block is likely not clearly realized.  What I mean by that is generally speaking, finally is most often acting on something that was opened up in a try block which isn't the case here.

**Comment by hazendaz** [comment]
@krisse7 Thanks for finding and fixing this.

**Pull request merged**
