### PR TITLE
Added continueContextsTimeout property to WaffleAuthenticatorBase for tomcat 6,7,8.

### PR DESCRIPTION
**Pull request by alanlavintman**
I have added support for external configuration of the continueContextTimeout property required by the WindowsAuthProvider. All WaffleAuthenticatorBase classes now override the start method in order to create an instance of the WindowsAuthProviderImpl.
I have checked all inherited classes to call their base and all unit tests passes.

### CODE REVIEW

**Comment by hazendaz** [comment]
Can you update the changelog for waffle found in the root folder as well as write some unit tests?  Additionally can you look at enhancing the examples to use this new functionality?

**Comment by alanlavintman** [comment]
Sure, updating this tonight :)

**Comment by hazendaz** [comment]
@alanlavintman If you want this pull request aplied, please update the changelogi and write some unit tests.  We will take this as soon as that is completed.  Thanks.

**Comment by hazendaz** [comment]
@alanlavintman Do you still want to get this pulled into waffle?  It's been about a year so I need to make a determination if this should come in or not.  If you do still want this, please make the same changes against the tomcat 9 version that is now present.

If I don't hear anything back I might still pull this in on my own but not sure on timetable there.  I'll want to thoroughly review it first and go from there.  I'm pretty busy otherwise with other things so if you can help, or really anyone else that reads these, that would be very welcomed.

**Comment by hazendaz** [comment]
@alanlavintman Do you still want this change?  I'm getting ready to push a release so if you do, please rebase this and add the support to tomcat 8.5 and 9.0 as well.

**Comment by hazendaz** [comment]
Merged per #579

**Pull request closed without merging**
